name: 'Workflow'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env-file
        run: cp .env.dist .env
      - name: lint docker-compose.yml
        run: docker compose config
